### ISSUE TITLE
Ejs Error

### ISSUE THREAD

**Issue by Vmain9** [RlxChap2/Tutorial#2]
**السلام عليكم ورحمة الله و بركاته** 

**عندي مشكلة في البوت و اللي هي لما اجي اشغل الداشبورد حق البوت يقولي عندك مشكلة في ال headers و ما يشتغل الموقع** 
**+ اعتقد في مشكلة بالبورت لان بالشرح انت مخليه 3000 و هنا بالاكواد مكتوبه 300** 

**+ في اخر فيديو لك انت ما ربطت الموقع ف ما ندري اذا هو الحين اشتغل ولا لا** 

**ف ياريت تقدر تحل لنا المشكلة و بالتوفيق لك يارب ❤️**

**Comment by RlxChap2** [comment]
**وعليكم السلام ورحمة الله و بركاته** 

**عدلت اكثر من شي و الموقع شغال تمام الحين و شكرا لك على انك قلت على المشكلة**

**و ياك يارب و باذن الله للاعلى❤️❤️🫡**

![image](https://github.com/RlxChap2/Tutorial/assets/133292635/b0c7bafc-1764-4475-927d-4fbefefcdcf2)
